repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # change as appropriate
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0  # change as appropriate
    hooks:
      - id: flake8
